# Generated by ChatGPT, heavily modified by me

from dotenv import load_dotenv
import streamlit as st
from mistralai.client import MistralClient
from mistralai.models.chat_completion import ChatMessage
import os

# Function to send requests to Mistralx API

# Streamlit app

load_dotenv()
api_key = os.environ["MISTRAL_API_KEY"]
model = "mistral-small"
client = MistralClient(api_key=api_key)
st.title("Conversation with Mistralx Model")

def send():
    # Send request to Mistralx API
    messages = [
        ChatMessage(role="user", content=user_input)
    ]
    response = client.chat(
    model=model,
    messages=messages,
    ).choices[0].message.content
    response


user_input = st.text_input("Enter your message:")
st.button("Send", on_click=send)

# User input

